### PR TITLE
Issue1217, 1212, 1215 Re-ordered named arguments seems to confuse type inference, + and -- operators use too much code, 2 Extra Pairs of Brackets

### LINKED ISSUE #1217: Re-ordered named arguments seems to confuse type inference
http://forums.bridge.net/forum/bridge-net-pro/bugs/2099-re-ordered-named-arguments-seems-to-confuse-type-inference

**UPD**: [Live Sample](http://live.bridge.net/#62b24d35a132c18bb6d48c5772296599)

### Expected
Correct generic argument in invocation

### Actual
Incorrect generic argument
```
go: function () {
    var navigatorTestWrapper = Demo.NavigatorTests.getNavigatorToTest(?, "", "", $_.Demo.NavigatorTests.f1);
},
```

### Steps To Reproduce

```csharp
public static class NavigatorTests
{
    [Ready]
    public static void Go()
    {
        var navigatorTestWrapper = GetNavigatorToTest(
            initialUrl: "",
            navigatorGenerator: () => (DemoNavigator)null,
            assert: ""
        );
    }
    
    private static int GetNavigatorToTest<TNavigator>(
        string initialUrl,
        string assert,
        Func<TNavigator> navigatorGenerator)
            where TNavigator : Navigator
    {
        throw new NotImplementedException();
    }
}

public class Navigator { }
public class DemoNavigator : Navigator { }
```

### PR DESCRIPTION
**Pull request by vladsch**
Fixes #1217, #1212, #1215

### CODE REVIEW

File: Tests/Runner/Batch1/code.js [hunk 1]
```diff
@@ -3561,10 +3565,10 @@ SomeExternalNamespace.SomeNonBridgeClass.prototype.foo = function(){return 1;};
                 i1 = i1.add(Bridge.Decimal(2));
                 Bridge.ClientTest.BridgeIssues.Bridge1041.Bridge1041Decimal.assertIsDecimalAndEqualTo(Bridge.Decimal(4.5), i1);
     
-                i1 = i1.add(Bridge.Decimal(1));
+                (i1 = i1.add(1));
```
Comment (LeonidVeriga) [inline Tests/Runner/Batch1/code.js]: @vladsch - redundant brackets (#1212)

File: Compiler/Translator/Utils/Preconverter.cs [hunk 2]
```diff
@@ -34,7 +35,12 @@ public override void VisitUnaryOperatorExpression(UnaryOperatorExpression unaryO
                 unaryOperatorExpression.Operator == UnaryOperatorType.Decrement ||
                 unaryOperatorExpression.Operator == UnaryOperatorType.PostDecrement)
             {
-                this.Found = true;
+                var rr = this.Resolver.ResolveNode(unaryOperatorExpression, null);
```
Comment (LeonidVeriga) [inline Compiler/Translator/Utils/Preconverter.cs]: #1212

File: Compiler/Translator/Utils/Preconverter.cs [hunk 3]
```diff
@@ -105,13 +123,47 @@ protected override AstNode VisitChildren(AstNode node)
...
+        }
+
         public override AstNode VisitUnaryOperatorExpression(UnaryOperatorExpression unaryOperatorExpression)
         {
             if (unaryOperatorExpression.Operator == UnaryOperatorType.Increment ||
                 unaryOperatorExpression.Operator == UnaryOperatorType.PostIncrement ||
                 unaryOperatorExpression.Operator == UnaryOperatorType.Decrement ||
                 unaryOperatorExpression.Operator == UnaryOperatorType.PostDecrement)
             {
+                var rr = this.Resolver.ResolveNode(unaryOperatorExpression, null);
```
Comment (LeonidVeriga) [inline Compiler/Translator/Utils/Preconverter.cs]: #1212
