### PR TITLE
[1615, 2508, 2902] StringBuilder indexer

### LINKED ISSUE #2508: StringBuilder.Chars Property (Int32)
Gets or sets the character at the specified character position in this instance.

### Steps To Reproduce

https://deck.net/ae0ed0c5c5b7814421ecf68080d478d5

```c#
public class Program
{
	public static void Main()
	{
		var sb = new StringBuilder();
		
		sb.Append("Hello World");
		
		char c1 = sb[6];
        
		// W		
		Console.WriteLine(c1);
	}
}
```

### Expected Result

```js
6
```

### Actual Result

```js
Argument 1: Cannot convert from 'string' to 'int'
```

## See Also

* #1615 
* #2902

### PR DESCRIPTION
**Pull request by vladsch**
[2508] StringBuilder.Chars Property (Int32)
[1615] StringBuilder - missing substring constructor
[2902] StringBuilder indexer should accept an int

Fixes #2508 #1615 #2902

### CODE REVIEW

File: Bridge/Resources/Text/StringBuilder.js [hunk 1]
```diff
@@ -233,5 +235,42 @@
...
+                this.$str = this.buffer.join("");
+                this.buffer = [];
+                this.buffer[0] = this.$str;
+            }
+
+            return this.$str;
+        },
+
+        getChar: function (index) {
+            var str = this.getString();
```
Comment (michaelcheers) [inline Bridge/Resources/Text/StringBuilder.js]: Isn't this a bit slow?

File: Bridge/Resources/Text/StringBuilder.js [hunk 2]
```diff
@@ -233,5 +235,42 @@
...
+
+        setChar: function(index, value) {
+            var str = this.getString();
+            if (index < 0 || index >= str.length) {
+                throw new System.ArgumentOutOfRangeException();
+            }
+
+            value = String.fromCharCode(value);
+            this.buffer = [];
+            this.buffer[0] = str.substring(0, index);
```
Comment (michaelcheers) [inline Bridge/Resources/Text/StringBuilder.js]: Isn't this slow too?
