### PR TITLE
[2929] DateTime kind and timezones

### LINKED ISSUE #2929: DateTime.ToUniversalTime does not correctly set timezone
Running this code in the UK (currently GMT +1):

https://deck.net/cb6e5a85fd5bdab6f112a78061e4275c

```cs
var date = DateTime.Now;
       
Console.WriteLine(date.ToString("O"));
Console.WriteLine(date.ToUniversalTime().ToString("O"));
```

Outputs the following in Bridge:

```text
2017-07-05T11:21:55.7760000+01:00
2017-07-05T10:21:55.7760000+01:00
```

This is incorrect - the second time should be +0 (Z) not +1. This results us getting off-by-one errors when converting users local times into UTC times.

Here's the output from the same code running in .NET on a machine in the GMT +1 (BST) timezone:

https://dotnetfiddle.net/U1Virr

```text
2017-07-05T11:14:05.0309452+01:00
2017-07-05T10:14:05.0309452Z
```

## See Also

* Unexpected results of ToLocalTime() / ToUniversalTime() #2524

### PR DESCRIPTION
**Pull request by geoffreymcgill**
Fixes:
* DateTime.ToUniversalTime does not correctly set timezone #2929
* Unexpected results of ToLocalTime() / ToUniversalTime() #2524
* Date AddYears - Condition Operator ? #2963
* DateTime.MinValue is not UTC #2952
* DateTime AddDays may not be calculating correctly when spanning DSL #2967
* locale files updated (AM/PM designators, formats), related to https://github.com/bridgedotnet/Bridge/issues/2802#issuecomment-312859216

### CODE REVIEW

File: Bridge/System/SerializableAttribute.cs [hunk 1]
```diff
@@ -1,13 +1,28 @@
...
-    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct, Inherited = false)]
-    [External]
-    [NonScriptable]
+    using System;
+    using System.Reflection;
+
+    [Bridge.External]
+    [Bridge.NonScriptable]
+    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Delegate, Inherited = false)]
+    [System.Runtime.InteropServices.ComVisible(true)]
```
Comment (michaelcheers) [inline Bridge/System/SerializableAttribute.cs]: Will this cause merge conflicts with [#2787](https://github.com/bridgedotnet/Bridge/pull/2787/files#diff-aa20b2928072a71c14df167666fb45ec).
