### PR TITLE
[3994] Optional Parameters of Enum Types are not generated correctly

### LINKED ISSUE #3994: Optional Parameters of Enum Types are not generated correctly
Default Value is missing resulting in a syntax error in js code.

### Steps To Reproduce

https://deck.net/3e3dc8f8816cc012ef19116cded7ba61

```csharp
public class Program
{
    public void TestFnc(TestEnum testEnum = TestEnum.Test) { }
}

public enum TestEnum
{
    Test,
    Test01
}
```

### Expected Result

```js
TestFnc: function (testEnum) {
                if (testEnum === void 0) { testEnum = 0; }
            }
```

### Actual Result

```js
TestFnc: function (testEnum) {
                if (testEnum === void 0) { testEnum = ; }
            }
```

### See Also
https://forums.bridge.net/forum/community/help/6225-optional-paramters-of-enum-types-are-not-generated-correctly-in-version-17-8

### PR DESCRIPTION
**Pull request by vladsch**
Fixes #3994

### CODE REVIEW

File: Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs [hunk 1]
```diff
@@ -224,7 +224,7 @@ protected IAsyncStep WriteAwaiter(AstNode node)
             this.Write(JS.Vars.ASYNC_TASK + index + ".isCompleted()");
 
             this.WriteCloseParentheses();
-            this.Write(" continue;");
+            this.Write(" { continue; }");
```
Comment (fabriciomurta) [inline Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs]: This change is related to issue #3963 (pr #3971).

Comment (fabriciomurta) [reply Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.cs]: As we chatted, wiped this commit as it is unrelated to this pull request, and will include it via another separate pr.

File: Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs [hunk 2]
```diff
@@ -291,6 +288,9 @@ public virtual void ConvertParamsToReferences(IEnumerable<ParameterDeclaration>
                                             } else {
                                                 this.WriteScript(prm.ConstantValue);
                                             }
+                                        } else
```
Comment (fabriciomurta) [inline Compiler/Translator/Emitter/Blocks/AbstractEmitterBlock.Locals.cs]: bad, bad else. ctrl+k,d fixed it in commit 73f2d92195725c14b495ae0cc01fc69750b4e371
